export class Constants {
  public static INDEX_HTML: string = `<!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Welcome to AWS Hosting with S3 and Cloudfront</title>
    
        <style media="screen">
          body {
            background: #eceff1;
            color: rgba(0, 0, 0, 0.87);
            font-family: Roboto, Helvetica, Arial, sans-serif;
            margin: 0;
            padding: 0;
          }
          #message {
            background: white;
            max-width: 360px;
            margin: 100px auto 16px;
            padding: 32px 24px;
            border-radius: 3px;
          }
          #message h2 {
            color: #ffa100;
            font-weight: bold;
            font-size: 16px;
            margin: 0 0 8px;
          }
          #message h1 {
            font-size: 22px;
            font-weight: 300;
            color: rgba(0, 0, 0, 0.6);
            margin: 0 0 16px;
          }
          #message p {
            line-height: 140%;
            margin: 16px 0 24px;
            font-size: 14px;
          }
          #message a {
            display: block;
            text-align: center;
            background: #039be5;
            text-transform: uppercase;
            text-decoration: none;
            color: white;
            padding: 16px;
            border-radius: 4px;
          }
          #message,
          #message a {
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
          }
          #load {
            color: rgba(0, 0, 0, 0.4);
            text-align: center;
            font-size: 13px;
          }
          @media (max-width: 600px) {
            body,
            #message {
              margin-top: 0;
              background: white;
              box-shadow: none;
            }
            body {
              border-top: 16px solid #ffa100;
            }
          }
        </style>
      </head>
      <body>
        <div id="message">
          <h2>Welcome</h2>
          <h1>AWS Hosting Setup Complete</h1>
          <p>
            You're seeing this because you've successfully setup AWS Hosting. Now
            it's time to go build something extraordinary!
          </p>
          <a target="_blank" href="https://github.com/4l3j4ndr0/awstools">Open Hosting Documentation</a>
        </div>
      </body>
    </html>
    `;
  public static ERROR_HTML: string = `<!DOCTYPE html>
  <html>
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>Page Not Found</title>
  
      <style media="screen">
        body {
          background: #eceff1;
          color: rgba(0, 0, 0, 0.87);
          font-family: Roboto, Helvetica, Arial, sans-serif;
          margin: 0;
          padding: 0;
        }
        #message {
          background: white;
          max-width: 360px;
          margin: 100px auto 16px;
          padding: 32px 24px 16px;
          border-radius: 3px;
        }
        #message h3 {
          color: #888;
          font-weight: normal;
          font-size: 16px;
          margin: 16px 0 12px;
        }
        #message h2 {
          color: #ffa100;
          font-weight: bold;
          font-size: 16px;
          margin: 0 0 8px;
        }
        #message h1 {
          font-size: 22px;
          font-weight: 300;
          color: rgba(0, 0, 0, 0.6);
          margin: 0 0 16px;
        }
        #message p {
          line-height: 140%;
          margin: 16px 0 24px;
          font-size: 14px;
        }
        #message a {
          display: block;
          text-align: center;
          background: #039be5;
          text-transform: uppercase;
          text-decoration: none;
          color: white;
          padding: 16px;
          border-radius: 4px;
        }
        #message,
        #message a {
          box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
        }
        #load {
          color: rgba(0, 0, 0, 0.4);
          text-align: center;
          font-size: 13px;
        }
        @media (max-width: 600px) {
          body,
          #message {
            margin-top: 0;
            background: white;
            box-shadow: none;
          }
          body {
            border-top: 16px solid #ffa100;
          }
        }
      </style>
    </head>
    <body>
      <div id="message">
        <h2>404</h2>
        <h1>Page Not Found</h1>
        <p>
          The specified file was not found on this website. Please check the URL
          for mistakes and try again.
        </p>
        <h3>Why am I seeing this?</h3>
        <p>
          This page was generated by the awstool Command-Line Interface. To modify
          it, edit the <code>404.html</code> file in your project's configured
          <code>public</code> directory.
        </p>
      </div>
    </body>
  </html>
  `;

  public static NAME_CONFIG_FILE: string = "awsconfig.json";

  public static AWS_CONFIG_HOSTING(
    projectIdentifier: string,
    publicDirectory: string,
    rootFile: string,
    createCdn: boolean,
    hostedZoneId?: string,
    hostedZoneName?: string,
    recordName?: string,
  ) {
    return `
{
  "deployType": "hosting",
  "projectIdentifier": "${projectIdentifier}",
  "publicDirectory": "${publicDirectory}",
  "rootFile": "${rootFile}",
  "createCdn": ${createCdn},
  "route53" : ${
    hostedZoneId && recordName
      ? `{
    "hostedZoneId": "${hostedZoneId}",
    "hostedZoneName": "${hostedZoneName}",
    "recordName": "${recordName}"
  }`
      : null
  }
}`;
  }
}
